### ISSUE TITLE
BLOCKER: PSSA Errors Need to Be Fixed

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/xSCDPM#5]
Errors from PS script analyzer are causing the tests to fail like [this](https://ci.appveyor.com/project/PowerShell/xscdpm/build/1.2.25.0).
This resource module cannot be released until these errors are fixed or suppressed and the tests are passing.

**Comment by Indhukrishna** [comment]
#4

**Comment by kwirkykat** [comment]
This was fixed in #4
